title:            Henry Kuo
description:      "A middle school student in Hsinchu, Taiwan."
logo:             
disqus_shortname: hk49
# Assign a default image for your site's header and footer
default_bg:       background.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Turn on or off the fin animations in the header and footer
animated_fins:    true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
url:              "https://hk49.github.com" #"http://localhost:4000"

# Owner/author information
owner:
  name:           Henry Kuo
  avatar:         avatar.png
  email:          393ec996@opayq.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    "A middle school student in Hsinchu, Taiwan."
  # Social networking links used in footer. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        henryk8128
  facebook:
  github:         
  linkedin:
  instagram:
  tumblr:
  hmfaysalsocial:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "https://plus.google.com/u/0/110594372344903801831"

# Analytics and webmaster tools stuff goes here
google_analytics: UA-55184147-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: <i class="icon-book"></i> Documentation
    url: /documentation
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: Faysal who?
    url: /hossain-mohd-faysal

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Taipei
future:      true
pygments:    true
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class